---
title: 'OctaPi: calculating Pi'
hero_image: images/banner.png
description: Learn how to calculate Pi using the power of distributed computing
theme: navy
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-12-01
steps:
- title: Introduction
- title: What you will need
- title: Why is calculating π difficult?
- title: Viète's method
  completion:
  - engaged
- title: Representing decimals on a computer
- title: Dartboard method
- title: Dartboard algorithm on a standalone processor
- title: Comparing the two methods
- title: Dartboard algorithm on the OctaPi
  completion:
  - internal
- title: 'Challenge: optimising the dartboard method'
  completion:
  - external
